// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VocabTrainer.Infrastructure.Data;

#nullable disable

namespace VocabTrainer.Infrastructure.Migrations
{
    [DbContext(typeof(VocabTrainerDbContext))]
    [Migration("20260321171913_AddReviewEntity")]
    partial class AddReviewEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VocabTrainer.Domain.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.DeckEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VocabEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VocabEntryId");

                    b.HasIndex("DeckId", "VocabEntryId")
                        .IsUnique();

                    b.ToTable("DeckEntries");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.DeckLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("DeckId", "LessonId")
                        .IsUnique();

                    b.ToTable("DeckLessons");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VocabEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VocabEntryId");

                    b.HasIndex("DeckId", "VocabEntryId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.VocabEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<string>("EnglishTranslation")
                        .HasColumnType("text");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsClassified")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("VocabEntries");

                    b.HasDiscriminator<string>("EntryType").HasValue("VocabEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Expression", b =>
                {
                    b.HasBaseType("VocabTrainer.Domain.Models.VocabEntry");

                    b.HasDiscriminator().HasValue("Expression");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Noun", b =>
                {
                    b.HasBaseType("VocabTrainer.Domain.Models.VocabEntry");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPluralOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSingularOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("PluralForm")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Noun");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.DeckEntry", b =>
                {
                    b.HasOne("VocabTrainer.Domain.Models.Deck", null)
                        .WithMany("DeckEntries")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabTrainer.Domain.Models.VocabEntry", null)
                        .WithMany()
                        .HasForeignKey("VocabEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.DeckLesson", b =>
                {
                    b.HasOne("VocabTrainer.Domain.Models.Deck", null)
                        .WithMany("DeckLessons")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabTrainer.Domain.Models.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Lesson", b =>
                {
                    b.HasOne("VocabTrainer.Domain.Models.Course", null)
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Review", b =>
                {
                    b.HasOne("VocabTrainer.Domain.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabTrainer.Domain.Models.VocabEntry", null)
                        .WithMany()
                        .HasForeignKey("VocabEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.VocabEntry", b =>
                {
                    b.HasOne("VocabTrainer.Domain.Models.Lesson", "Lesson")
                        .WithMany("VocabEntries")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Deck", b =>
                {
                    b.Navigation("DeckEntries");

                    b.Navigation("DeckLessons");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Lesson", b =>
                {
                    b.Navigation("VocabEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
