// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VocabTrainer.Infrastructure.Data;

#nullable disable

namespace VocabTrainer.Infrastructure.Migrations
{
    [DbContext(typeof(VocabTrainerDbContext))]
    [Migration("20260202101730_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VocabTrainer.Domain.Models.VocabEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<string>("EnglishTranslation")
                        .HasColumnType("text");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VocabEntries");

                    b.HasDiscriminator<string>("EntryType").HasValue("VocabEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Expression", b =>
                {
                    b.HasBaseType("VocabTrainer.Domain.Models.VocabEntry");

                    b.HasDiscriminator().HasValue("Expression");
                });

            modelBuilder.Entity("VocabTrainer.Domain.Models.Noun", b =>
                {
                    b.HasBaseType("VocabTrainer.Domain.Models.VocabEntry");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPluralOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSingularOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("PluralForm")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Noun");
                });
#pragma warning restore 612, 618
        }
    }
}
